//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.Infrastructure.SqlScripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingService.Infrastructure.SqlScripts.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ApartmentId, AVG(DATEDIFF(DAY, StartDate, EndDate)) as AverageDuration
        ///                        FROM dbo.Bookings
        ///                        GROUP BY ApartmentId;.
        /// </summary>
        internal static string GetAverageBookingDurationPerApartment {
            get {
                return ResourceManager.GetString("GetAverageBookingDurationPerApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT u.UserName, SUM(b.TotalPrice) as TotalIncome 
        ///                        FROM dbo.AspNetUsers as u 
        ///                        INNER JOIN dbo.Apartments as a on a.HostId = u.Id 
        ///                        INNER JOIN dbo.Bookings as b on a.Id = b.ApartmentId 
        ///                        GROUP BY u.UserName;.
        /// </summary>
        internal static string GetHostsProfit {
            get {
                return ResourceManager.GetString("GetHostsProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id as ApartmentId, Price, NTILE(4) OVER (ORDER BY Price) AS Quantile
        ///                        FROM dbo.Apartments;.
        /// </summary>
        internal static string GetPriceQuantiles {
            get {
                return ResourceManager.GetString("GetPriceQuantiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT b.ApartmentId
        ///                    FROM dbo.Bookings as b
        ///                    GROUP BY b.ApartmentId, b.ClientId
        ///                    HAVING COUNT(*) &gt; 1;.
        /// </summary>
        internal static string GetRepeatedBookingPerApartmentClient {
            get {
                return ResourceManager.GetString("GetRepeatedBookingPerApartmentClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 5 ApartmentId, COUNT(*) AS BookingCount
        ///                        FROM dbo.Bookings
        ///                        GROUP BY ApartmentId 
        ///                        ORDER BY BookingCount DESC;.
        /// </summary>
        internal static string GetTop5MostBookingApartment {
            get {
                return ResourceManager.GetString("GetTop5MostBookingApartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO dbo.Apartments AS target
        ///USING (VALUES (@Id, @HostId, @CustomData)) AS source (Id, HostId, CustomData)
        ///ON target.Id = source.Id
        ///WHEN MATCHED THEN
        ///    UPDATE SET target.CustomData = source.CustomData
        ///WHEN NOT MATCHED THEN
        ///    INSERT (HostId, CustomData)
        ///    VALUES (source.HostId, source.CustomData);.
        /// </summary>
        internal static string UpsertApartmentCustomData {
            get {
                return ResourceManager.GetString("UpsertApartmentCustomData", resourceCulture);
            }
        }
    }
}
